### ISSUE TITLE
移植到 Firefox

### ISSUE THREAD

**Issue by Riajyuu** [solobat/wordcard#1]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions

**Comment by solobat** [comment]
有这计划

**Comment by midpoint** [comment]
挺好用的，等待 firefox版

**Comment by solobat** [comment]
各位，移植 Firefox 版已经上架了

> 唯一差别是，双击取词成为默认设置了

[FireFox 附加组件](https://addons.mozilla.org/zh-CN/firefox/addon/%E5%8D%95%E8%AF%8D%E5%B0%8F%E5%8D%A1%E7%89%87-%E6%9F%A5%E8%AF%8D-%E6%94%B6%E9%9B%86-%E8%83%8C%E5%8D%95%E8%AF%8D/)

另外，代码在 `FIREFOX`分支上

**Comment by midpoint** [comment]
很好用，辛苦了！！！
