### ISSUE TITLE
五角星不见了

### ISSUE THREAD

**Issue by jzwz** [solobat/wordcard#2]
https://cppdepend.com/blog/
这个网站的单词，双击后，没有收藏的五角星，最好能提供一个选项：查询单词后，直接加入单词列表

**Comment by solobat** [comment]
- 稍后我适配一下。
在修复之前，可以按图示双击标题栏来收藏：
![Imgur](https://i.imgur.com/n0Gq3BF.png)

- 直接加入单词列表
受限于 chrome.storage.sync 的 api 限制，如果自动加入单词列表很容易导致容量用完，所以需要等有了替代方案以后再加这个功能
